"""Initial VIGIL-RAG schema

Revision ID: 4033bc64052e
Revises:
Create Date: 2026-02-12 10:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4033bc64052e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create videos table
    op.create_table('videos',
        sa.Column('video_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('file_path', sa.Text(), nullable=False),
        sa.Column('task_id', sa.String(length=200), nullable=True),
        sa.Column('role', sa.String(length=20), nullable=True),
        sa.Column('site_id', sa.String(length=100), nullable=True),
        sa.Column('camera_id', sa.String(length=100), nullable=True),
        sa.Column('operator_id_hash', sa.String(length=100), nullable=True),
        sa.Column('num_clips', sa.Integer(), nullable=True),
        sa.Column('embedding_model', sa.String(length=100), nullable=True),
        sa.Column('created_at', sa.Text(), nullable=True),
        sa.Column('uri', sa.Text(), nullable=True),
        sa.Column('storage_path', sa.Text(), nullable=True),
        sa.Column('duration_sec', sa.Float(), nullable=True),
        sa.Column('fps', sa.Float(), nullable=True),
        sa.Column('width', sa.Integer(), nullable=True),
        sa.Column('height', sa.Integer(), nullable=True),
        sa.Column('domain', sa.String(length=50), nullable=True),
        sa.Column('checksum', sa.String(length=64), nullable=True),
        sa.Column('ingest_time', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('video_id'),
        sa.UniqueConstraint('file_path')
    )
    op.create_index('idx_videos_domain_camera', 'videos', ['domain', 'camera_id'], unique=False)
    op.create_index(op.f('ix_videos_camera_id'), 'videos', ['camera_id'], unique=False)
    op.create_index(op.f('ix_videos_domain'), 'videos', ['domain'], unique=False)
    op.create_index(op.f('ix_videos_site_id'), 'videos', ['site_id'], unique=False)
    op.create_index(op.f('ix_videos_task_id'), 'videos', ['task_id'], unique=False)

    # Create embeddings table
    op.create_table('embeddings',
        sa.Column('embedding_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('model_name', sa.String(length=100), nullable=False),
        sa.Column('model_version', sa.String(length=50), nullable=True),
        sa.Column('dimension', sa.Integer(), nullable=False),
        sa.Column('vector_ref', sa.Text(), nullable=True),
        sa.Column('created_at', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('embedding_id')
    )
    op.create_index('idx_embeddings_model', 'embeddings', ['model_name', 'model_version'], unique=False)

    # Create clips table
    op.create_table('clips',
        sa.Column('clip_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('video_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('level', sa.String(length=20), nullable=False),
        sa.Column('start_sec', sa.Float(), nullable=False),
        sa.Column('end_sec', sa.Float(), nullable=False),
        sa.Column('keyframe_paths', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('transcript_text', sa.Text(), nullable=True),
        sa.Column('embedding_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('clip_idx', sa.Integer(), nullable=True),
        sa.CheckConstraint('end_sec > start_sec', name='check_clip_time_valid'),
        sa.ForeignKeyConstraint(['embedding_id'], ['embeddings.embedding_id'], ),
        sa.ForeignKeyConstraint(['video_id'], ['videos.video_id'], ),
        sa.PrimaryKeyConstraint('clip_id')
    )
    op.create_index('idx_clips_time_range', 'clips', ['video_id', 'start_sec', 'end_sec'], unique=False)
    op.create_index('idx_clips_video_level', 'clips', ['video_id', 'level'], unique=False)
    op.create_index(op.f('ix_clips_embedding_id'), 'clips', ['embedding_id'], unique=False)
    op.create_index(op.f('ix_clips_level'), 'clips', ['level'], unique=False)
    op.create_index(op.f('ix_clips_video_id'), 'clips', ['video_id'], unique=False)

    # Create events table
    op.create_table('events',
        sa.Column('event_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('video_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('event_type', sa.String(length=100), nullable=False),
        sa.Column('start_sec', sa.Float(), nullable=False),
        sa.Column('end_sec', sa.Float(), nullable=False),
        sa.Column('confidence', sa.Float(), nullable=False),
        sa.Column('method', sa.String(length=50), nullable=False),
        sa.Column('evidence_clip_ids', postgresql.ARRAY(postgresql.UUID(as_uuid=True)), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('reviewed_by', sa.String(length=100), nullable=True),
        sa.Column('reviewed_at', sa.Text(), nullable=True),
        sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.Text(), nullable=True),
        sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='check_confidence_range'),
        sa.CheckConstraint('end_sec > start_sec', name='check_event_time_valid'),
        sa.ForeignKeyConstraint(['video_id'], ['videos.video_id'], ),
        sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('idx_events_type_status', 'events', ['event_type', 'status'], unique=False)
    op.create_index('idx_events_video_time', 'events', ['video_id', 'start_sec', 'end_sec'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_video_id'), 'events', ['video_id'], unique=False)

    # Create ingest_jobs table (SOPilot backward compat)
    op.create_table('ingest_jobs',
        sa.Column('job_id', sa.String(length=100), nullable=False),
        sa.Column('video_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('task_id', sa.String(length=200), nullable=True),
        sa.Column('role', sa.String(length=20), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('queued_at', sa.Text(), nullable=True),
        sa.Column('started_at', sa.Text(), nullable=True),
        sa.Column('finished_at', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['video_id'], ['videos.video_id'], ),
        sa.PrimaryKeyConstraint('job_id')
    )

    # Create queries table (RAG analytics)
    op.create_table('queries',
        sa.Column('query_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('video_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('question', sa.Text(), nullable=False),
        sa.Column('answer', sa.Text(), nullable=True),
        sa.Column('confidence', sa.Float(), nullable=True),
        sa.Column('retrieved_clip_ids', postgresql.ARRAY(postgresql.UUID(as_uuid=True)), nullable=True),
        sa.Column('retrieval_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('embedding_model', sa.String(length=100), nullable=True),
        sa.Column('llm_model', sa.String(length=100), nullable=True),
        sa.Column('feedback', sa.String(length=20), nullable=True),
        sa.Column('feedback_comment', sa.Text(), nullable=True),
        sa.Column('query_time', sa.Text(), nullable=True),
        sa.Column('response_latency_sec', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(['video_id'], ['videos.video_id'], ),
        sa.PrimaryKeyConstraint('query_id')
    )
    op.create_index('idx_queries_video_time', 'queries', ['video_id', 'query_time'], unique=False)
    op.create_index(op.f('ix_queries_video_id'), 'queries', ['video_id'], unique=False)

    # Create score_jobs table (SOPilot backward compat)
    op.create_table('score_jobs',
        sa.Column('job_id', sa.String(length=100), nullable=False),
        sa.Column('gold_video_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('trainee_video_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('score', sa.Float(), nullable=True),
        sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('queued_at', sa.Text(), nullable=True),
        sa.Column('started_at', sa.Text(), nullable=True),
        sa.Column('finished_at', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['gold_video_id'], ['videos.video_id'], ),
        sa.ForeignKeyConstraint(['trainee_video_id'], ['videos.video_id'], ),
        sa.PrimaryKeyConstraint('job_id')
    )

    # Create training_jobs table (SOPilot backward compat)
    op.create_table('training_jobs',
        sa.Column('job_id', sa.String(length=100), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('trigger', sa.String(length=50), nullable=True),
        sa.Column('result_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('queued_at', sa.Text(), nullable=True),
        sa.Column('started_at', sa.Text(), nullable=True),
        sa.Column('finished_at', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('job_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_jobs')
    op.drop_table('score_jobs')
    op.drop_index(op.f('ix_queries_video_id'), table_name='queries')
    op.drop_index('idx_queries_video_time', table_name='queries')
    op.drop_table('queries')
    op.drop_table('ingest_jobs')
    op.drop_index(op.f('ix_events_video_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index('idx_events_video_time', table_name='events')
    op.drop_index('idx_events_type_status', table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_clips_video_id'), table_name='clips')
    op.drop_index(op.f('ix_clips_level'), table_name='clips')
    op.drop_index(op.f('ix_clips_embedding_id'), table_name='clips')
    op.drop_index('idx_clips_video_level', table_name='clips')
    op.drop_index('idx_clips_time_range', table_name='clips')
    op.drop_table('clips')
    op.drop_index('idx_embeddings_model', table_name='embeddings')
    op.drop_table('embeddings')
    op.drop_index(op.f('ix_videos_task_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_site_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_domain'), table_name='videos')
    op.drop_index(op.f('ix_videos_camera_id'), table_name='videos')
    op.drop_index('idx_videos_domain_camera', table_name='videos')
    op.drop_table('videos')
    # ### end Alembic commands ###
